---
# Path where the code must be deployed to
ansistrano_deploy_to: "/var/www/my-app"

# Folder name for the releases
ansistrano_version_dir: "releases"

# Softlink name for the current release
ansistrano_current_dir: "current"
